run:
  deadline: 1m
  tests: true

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - revive
    - ineffassign
    - nakedret
    - prealloc
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
  fast: false

linters-settings:
  errcheck:
    check-blank: true
  govet:
    shadow: true
  revive:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 30
  dupl:
    threshold: 200
  nakedret:
    max-func-lines: 50
  funlen:
    lines: 80
    statements: 50


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"
    - "always receives"
    - "parameter .* is always"
    - "comment on exported .* should be of the form"

output:
  formats: colored-line-number
