
version: '3.8'

services:

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: "service_healthy"
      redis:
        condition: "service_started"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  database:
    image: postgres:latest

    environment:
      - "POSTGRES_DB=avito_dev"
      - "POSTGRES_USER=grandeas"
      - "POSTGRES_PASSWORD=grandeas"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U grandeas -d avito_dev" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./bd_init.sql:/docker-entrypoint-initdb.d/bd_init.sql







