
version: '3.8'

services:

  database:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=avito_dev"
      - "POSTGRES_USER=grandeas"
      - "POSTGRES_PASSWORD=grandeas"
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        ipv4_address: 127.0.0.1
    volumes:
      - ./bd_init.sql:/docker-entrypoint-initdb.d/bd_init.sql

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      mynetwork:
        ipv4_address: 127.0.0.1

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "127.0.0.0/8"
