
app:
http:
  host: "0.0.0.0"
  port: 8000
  read-timeout: "5s"
  write-timeout: "10s"
  idle-timeout: "120s"
  read-header-timeout: "7s"
  re-request: "1s"
  cors:

    allowed-methods: [ "GET", "POST", "PATCH", "PUT", "OPTIONS", "DELETE" ]
    allowed-origins:
      - "*"
    allow-credentials: true
    allowed-headers:
      - "Authorization"
      - "token"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options-passthrough: true
    exposed-headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"


psql:
  host: "database"
  port: 5432
  username: "grandeas"
  password: "grandeas"
  database: "avito_dev"
  timeout: "2s"
  limit-max: 1000

cron:
  interval: '5m'


redis:
  host: "redis"
  port: 6379
  ttl: "5m"
  len-stack: 3
  timeout: "2s"

